### ISSUE TITLE
Error on fresh install for !fb help

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-facebook#16] opened 2019-05-14 01:43 UTC
```
[2019-05-14 01:42:13,769] [ERROR@mau.commands] Unhandled error while handling command help  from @travis:t2l.io (ref: 1557798028)
Traceback (most recent call last):
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 366, in handle
    await handler(evt)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/handler.py", line 267, in __call__
    return await self._handler(evt)
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/meta.py", line 60, in help_cmd
    return await evt.reply(_get_management_status(evt) + "\n" + await _get_help_text(evt))
  File "/home/facebook/fbenv/lib/python3.6/site-packages/mautrix/bridge/commands/meta.py", line 38, in _get_help_text
    if handler.has_help and handler.has_permission(cache_key):
  File "/home/facebook/mautrix-facebook/mautrix_facebook/commands/handler.py", line 59, in has_permission
    (not self.needs_auth or key.is_logged_in))
AttributeError: 'HelpCacheKey' object has no attribute 'is_logged_in'

```

**Comment by tulir** [comment] 2019-05-14 05:53
Duplicate of #15

**Closed by tulir** 2019-05-14 05:53 UTC
Labels: duplicate
