### ISSUE TITLE
Unhandled error on sync try

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-facebook#66] opened 2020-06-10 23:09 UTC
```
$ sync

Unhandled error while handling command:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync
    await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 968, in backfill
    elif last_active and most_recent.date >= last_active:
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'

$ sync --create

Unhandled error while handling command:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync
    await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 968, in backfill
    elif last_active and most_recent.date >= last_active:
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'

$ sync --contacts

Unhandled error while handling command:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 359, in handle
    await self._run_handler(handler, evt)
  File "/usr/lib/python3.8/site-packages/mautrix/bridge/commands/handler.py", line 253, in __call__
    return await self._handler(evt)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/commands/facebook.py", line 78, in sync
    await portal.backfill(evt.sender, is_initial=False, last_active=thread.last_active)
  File "/usr/lib/python3.8/site-packages/mautrix_facebook/portal.py", line 968, in backfill
    elif last_active and most_recent.date >= last_active:
TypeError: '>=' not supported between instances of 'NoneType' and 'datetime.datetime'

```

**Comment by tulir** [comment] 2020-06-11 11:13
Sounds like an outdated bridge and a duplicate of #57

**Comment by JuniorJPDJ** [comment] 2020-06-11 11:45
Bridge was build using docker from master.
There's part of my compose:
```
  mautrix-facebook:
    build: https://github.com/tulir/mautrix-facebook.git
```

```
$ version
mautrix-facebook 0.1.0rc3+dev.d62c4939
```

**Comment by JuniorJPDJ** [comment] 2020-06-11 11:46
Look - `most_recent.date` is None ;/

**Closed** 2020-06-11 13:35 UTC
